package cli

import (
	"html/template"
	"io"
	"time"

	"github.com/sailwalpranjal/appwrite-migration-guard/internal/version"
)

// writeChecklistHTML renders a ChecklistResult (from `amg doctor
// --json`/`amg preflight --json`) as a self-contained HTML document —
// no external stylesheet, script, font, or image reference of any
// kind, so it works when opened directly from disk with no network
// access. Visually consistent with internal/report's compare-result
// HTML (same CSS custom properties, dark mode, filled status badges)
// but a separate, much simpler template: a checklist has no findings
// table, no resource breakdown, no filter toolbar to justify — building
// a shared abstraction between two genuinely different result shapes
// for the sake of DRY would be the kind of unnecessary abstraction this
// project deliberately avoids. Living in internal/cli (not
// internal/report) avoids an import cycle: ChecklistResult is defined
// here, and internal/report is written specifically for compare.Result.
func writeChecklistHTML(w io.Writer, res ChecklistResult) error {
	data := checklistTemplateData{
		Title:       "amg report: " + res.Command,
		Result:      res,
		Overall:     overallOfChecks(res.Checks), // never the deserialized field — see overallOfChecks
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
		ToolVersion: version.Version,
	}
	return checklistHTMLTemplate.Execute(w, data)
}

type checklistTemplateData struct {
	Title       string
	Result      ChecklistResult
	Overall     Status
	GeneratedAt string
	ToolVersion string
}

var checklistHTMLTemplate = template.Must(template.New("checklist-report").Parse(checklistHTMLTemplateSource))

const checklistHTMLTemplateSource = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{.Title}}</title>
<style>
  :root {
    color-scheme: light dark;
    --pass: #1a7f37; --pass-bg: #dafbe1;
    --warn: #9a6700; --warn-bg: #fff8c5;
    --block: #cf222e; --block-bg: #ffebe9;
    --bg: #ffffff; --bg-alt: #f6f8fa; --fg: #1f2328; --border: #d0d7de; --muted: #656d76;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --pass: #3fb950; --pass-bg: #122117;
      --warn: #d29922; --warn-bg: #2b2111;
      --block: #f85149; --block-bg: #2d1214;
      --bg: #0d1117; --bg-alt: #161b22; --fg: #e6edf3; --border: #30363d; --muted: #8b949e;
    }
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; padding: 24px 16px 48px;
    background: var(--bg); color: var(--fg);
    font: 15px/1.5 -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  }
  main { max-width: 760px; margin: 0 auto; }
  h1 { font-size: 1.5rem; margin: 0 0 16px; }
  .badge {
    display: inline-block; padding: 4px 12px; border-radius: 6px;
    font-weight: 700; font-size: 0.95rem; letter-spacing: 0.02em;
    border: 1px solid currentColor;
  }
  .badge-PASS { color: var(--pass); background: var(--pass-bg); }
  .badge-WARN { color: var(--warn); background: var(--warn-bg); }
  .badge-BLOCK { color: var(--block); background: var(--block-bg); }
  table { width: 100%; border-collapse: collapse; margin-top: 16px; }
  th, td {
    text-align: left; padding: 10px 12px; border-bottom: 1px solid var(--border);
    vertical-align: top; font-size: 0.92rem;
  }
  th { font-size: 0.78rem; text-transform: uppercase; letter-spacing: 0.04em; color: var(--muted); }
  tbody tr:nth-child(even) { background: var(--bg-alt); }
  td.status { white-space: nowrap; font-weight: 700; }
  td.status.PASS { color: var(--pass); }
  td.status.WARN { color: var(--warn); }
  td.status.BLOCK { color: var(--block); }
  footer { margin-top: 32px; color: var(--muted); font-size: 0.8rem; }
</style>
</head>
<body>
<main>
  <h1>Appwrite Migration Guard — {{.Result.Command}}</h1>
  <p style="color:var(--muted);font-size:0.9rem">Generated {{.GeneratedAt}}</p>
  <span class="badge badge-{{.Overall}}">Result: {{.Overall}}</span>
  <table>
    <thead><tr><th scope="col">Status</th><th scope="col">Check</th><th scope="col">Detail</th></tr></thead>
    <tbody>
      {{range .Result.Checks}}
      <tr>
        <td class="status {{.Status}}">{{.Status}}</td>
        <td>{{.Title}}</td>
        <td>{{.Detail}}</td>
      </tr>
      {{end}}
    </tbody>
  </table>
  <footer>Generated by amg {{.ToolVersion}}. This report never contains API keys or other credentials.</footer>
</main>
</body>
</html>
`
